version: '3.2'
services:
  sql-server-db:
    container_name: sql-server-FastFlightFinderDb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Password_2_Change_4_Real_Cases_&'
      ACCEPT_EULA: 'Y'
      
      